apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ticketing
manifests:
  rawYaml:
    - ./infra/k8s/*
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: local
    build:
      local:
        push: false
build:
  artifacts:
    - image: auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .